### ISSUE TITLE
添加UTF8数据自动转化为GB2312的流程

### ISSUE THREAD

**Issue by CovMat** [gmt-china/china-geospatial-data#14]
中国断层数据中，添加断层中文名需要

**Comment by seisman** [comment]
使用如下命令将 UTF8 数据转换成了 GB2312 数据。
```
iconv -f UTF-8 -t GB2312 < CN-faults.gmt > CN-faults.GB2312.gmt
```

[CN-faults.GB2312.gmt.zip](https://github.com/gmt-china/china-geospatial-data/files/6582401/CN-faults.GB2312.gmt.zip)

请下载该数据并确认在Windows下GMT是否可以正常显示中文。

**Comment by core-man** [comment]
See [iconv](https://man.linuxde.net/iconv)

**Comment by CovMat** [comment]
> 使用如下命令将 UTF8 数据转换成了 GB2312 数据。
> 
> ```
> iconv -f UTF-8 -t GB2312 < CN-faults.gmt > CN-faults.GB2312.gmt
> ```
> 
> [CN-faults.GB2312.gmt.zip](https://github.com/gmt-china/china-geospatial-data/files/6582401/CN-faults.GB2312.gmt.zip)
> 
> 请下载该数据并确认在Windows下GMT是否可以正常显示中文。

测试了，可以使用
