### ISSUE TITLE
重建 git 历史

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#16]
由于在 commit 0eb46b14dfcdead80e615016717a60d27d0d0bce 中错误加入了 GB2312 数据。是否要趁着整个repo刚开始的时候重建 git 历史，以使得 repo 更小。

**Comment by core-man** [comment]
那个文件有多大？

**Comment by seisman** [comment]
700 KB.

**Comment by core-man** [comment]
可以考虑重新开始，毕竟现在基本是空的。Ping @CovMat for comment.

**Comment by seisman** [comment]
Done. Please re-clone the repository.
