### ISSUE TITLE
About

### ISSUE THREAD

**Issue by core-man** [gmt-china/china-geospatial-data#23]
`China's Geospatial Data for GMT` to `Geospatial Data used in GMT for China`?

**Comment by seisman** [comment]
To me, neither is satisfactory.

**Comment by core-man** [comment]
Ping @gmt-china/contributors for the comments.

**Comment by wangliang1989** [comment]
Geospatial Data of China

**Comment by seisman** [comment]
Geospatial Data of China for GMT?

**Comment by core-man** [comment]
China Geospatial Data for GMT?

**Comment by seisman** [comment]
Sounds good. I've updated the project information.

**Comment by wangliang1989** [comment]
不是gmt也可以用，可以不写gmt

**Comment by seisman** [comment]
数据主要面向GMT用户，其他人不管。
