### ISSUE TITLE
添加版本号信息？

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#25]
把下面这段代码加到 README 里，
```
![GitHub release (latest by date)](https://img.shields.io/github/v/release/gmt-china/china-geospatial-data)
```
会生成如下 badge:
![GitHub release (latest by date)](https://img.shields.io/github/v/release/gmt-china/china-geospatial-data)

这样可以很容易知道 china-geospatial-data 的最新版本是多少。

---

另一方面，在 README.md 也加上
```
当前数据版本号: v0.1.0
```

这样当用户下载了 v0.1.0 而我们发布了 v0.2.0 的时候，用户会查看 README.md 时会看到：

- 当前数据版本号: v0.1.0
- 最新数据版本号: 由 badge 动态生成的版本号，例如 v0.2.0

这样似乎可以更好地提醒用户下载新版本？

**Comment by core-man** [comment]
yes to me
