### ISSUE TITLE
更新日志

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#26]
是否应该加一个 changelog.md 文件，并且也包含到下载的数据包里？

这样用户就知道每个版本之间新增或修正了哪些数据？

**Comment by core-man** [comment]
yes to me. Shall we add a skip changelog label then?

**Comment by seisman** [comment]
English or Chinese for the changelog?

**Comment by core-man** [comment]
Chinese? I believe most users are Chinese.
