### ISSUE TITLE
新增英文版本 README?

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#28]

**Comment by core-man** [comment]
我觉得可以，但是可以等到我们有更多少数据集的时候，现在维护英文过早。可以等1.0发布的时候考虑。

**Comment by core-man** [comment]
CN-border-L1.gmt 的注释需要更新

**Comment by core-man** [comment]
目前数据集的构建和教程流程已经初步建立，我觉得可以开始新增英文版本 README 了。我们是在同一个 README 里新增，还是建立 README-cn.md 和 README-en.md 两个文件呢？

**Comment by seisman** [comment]
README 和README-en?

**Comment by core-man** [comment]
> README 和README-en?

Sound good~ Also add an English note in README.md to tell users we have an English README in `README-en.md`?

**Comment by seisman** [comment]
> > README 和README-en?
> 
> Sound good~ Also add an English note in `README.md` to tell users we have an English README in `README-en.md`?

Yes
