### ISSUE TITLE
中国地质图数据

### ISSUE THREAD

**Issue by CovMat** [gmt-china/china-geospatial-data#3]
原始数据来源：https://catalog.data.gov/dataset/generalized-geology-of-the-far-east-geo3al

数据处理方式：
https://jimmytseng79.github.io/GMT5_tutorials/geology_map.html

gmt用的数据来源：
https://blog.xumijian.me/post/gmt-geo/

徐弥坚处理得到的数据。是否可以直接收录？

**Comment by CovMat** [comment]
@seisman  @core-man 
能不能讨论一下这个数据要不要收入？

**Comment by core-man** [comment]
这个数据没有 License。看起来可以收入，9.1 MB。

>  License: No license information was provided. If this work was prepared by an officer or employee of the United States government as part of that person's official duties it is considered a U.S. Government Work.

**Comment by CovMat** [comment]
@core-man  @seisman  @wangliang1989 
老数据库迁移工作基本结束了。我想开始讨论一下这个要不要收录

**Comment by seisman** [comment]
看上去是OK的，但是这个用的人多么。

**Comment by CovMat** [comment]
很多。之前群里就一直有人问怎么画地质图，不少人都是地质专业的在用GMT

**Comment by seisman** [comment]
OK.

**Comment by wangliang1989** [comment]
我认为可以收录

**Comment by core-man** [comment]
看起来大家都支持。@CovMat 可以把这个 issue 分配给你吗 ？另外，如果可以请每个PR尽量小，并在关键修改的地方留你认为有必要的comment，以便每个PR能快速地被大家review和接收。
