### ISSUE TITLE
中国行政区划数据

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#38]
1. GMT的dcw数据中提供了中国各省的省界数据，但不确定其准确性如何
2. 社区目前提供的边界数据（http://gmt-china.org/example/ex003/ ）中省界与国界合在一起，难以单独提取出某个省份的边界数据。

**Comment by core-man** [comment]
FYI, I transferred the issue from gmt-china.org to this repo.

**Comment by core-man** [comment]
@CovMat would you like to help with this issue?

**Comment by seisman** [comment]
We will have an updates dataset for this

**Comment by seisman** [comment]
I don't know. I got some files from @liuzhumei, but I never had time to work on it.

**Comment by seisman** [comment]
See https://github.com/gmt-china/china-geospatial-data/issues/41
