### ISSUE TITLE
更新 CN-faults 数据

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#40]
目前的数据是: https://github.com/gmt-china/china-geospatial-data/blob/master/CN-faults.gmt

@liuzhumei 曾经给了我另一个版本，[CN-faults.gmt.zip](https://github.com/gmt-china/china-geospatial-data/files/6679539/CN-faults.gmt.zip)

这两个版本在某些细节上是不一样的。

@liuzhumei 请帮忙确认哪个版本才是正确的，并提供从原始数据得到 .gmt 数据的处理流程。

**Comment by liuzhumei** [comment]
目前的数据都是从个人渠道获得，所以存在不同时期版本的差异。现在我找到了官方版，并基于此提供一个最终版本吧。 [1/400万中国活动构造](http://datashare.igl.earthquake.cn/map/ActiveFault/introFault.html)

**Comment by liuzhumei** [comment]
> 目前的数据都是从个人渠道获得，所以存在不同时期版本的差异。现在我找到了官方版，并基于此提供一个最终版本吧。 [1/400万中国活动构造](http://datashare.igl.earthquake.cn/map/ActiveFault/introFault.html)

这个官方版数据里有明显的错误，比如属性字段名“分段年龄”错写成了“分段魂龄”，多个字段名不完整，包括“地震地_1”（应为“地震地表破裂带长度”），而我手里找人要来的数据要完整的多，那么我们应该做“数据的搬运工”，不管这些错误呢，还是把他修改完整呢？ 我倾向于前者……

**Comment by core-man** [comment]
> > 目前的数据都是从个人渠道获得，所以存在不同时期版本的差异。现在我找到了官方版，并基于此提供一个最终版本吧。 [1/400万中国活动构造](http://datashare.igl.earthquake.cn/map/ActiveFault/introFault.html)
> 
> 这个官方版数据里有明显的错误，比如属性字段名“分段年龄”错写成了“分段魂龄”，多个字段名不完整，包括“地震地_1”（应为“地震地表破裂带长度”），而我手里找人要来的数据要完整的多，那么我们应该做“数据的搬运工”，不管这些错误呢，还是把他修改完整呢？ 我倾向于前者……

最好是能有一套从原始数据到最终数据集的流程，如 https://github.com/gmt-china/GMT_docs/pull/364 建立中国区域地质图的过程。数据如果有问题，需要修正和维护才发布。

**Comment by liuzhumei** [comment]
我参考了[gmt-china/GMT_docs#427](https://github.com/gmt-china/GMT_docs/pull/427) 的格式修改了中国断层数据集的描述、使用方法和构建流程，包含了 [gmt-china/GMT_docs#428](https://github.com/gmt-china/GMT_docs/issues/428)的原有内容。

在这篇介绍中尚有几个问题待讨论：

1. 原文中说 **-Sq** 不支持中文，但在我这里是支持的，有待大家验证
2. 不能通过 ` plot CN-faults.gmt -Sqn1:+Lh  -aL="断层名称" ` 一次性绘制断层标注，只能通过 `gmt convert` 转一道，这似乎是bug，我记得跟 @seisman 讨论过
3. 结尾处的中文引用是[原网站](http://datashare.igl.earthquake.cn/map/ActiveFault/introFault.html)中提供的，英文引用是我自己查的，不知道合适不合适。

[CN-faults.md](https://github.com/gmt-china/china-geospatial-data/files/6690863/CN-faults.md)
[CN-faults.zip](https://github.com/gmt-china/china-geospatial-data/files/6690920/CN-faults.zip)

**Comment by core-man** [comment]
> 我参考了[gmt-china/GMT_docs#427](https://github.com/gmt-china/GMT_docs/pull/427) 的格式修改了中国断层数据集的描述、使用方法和构建流程，包含了 [gmt-china/GMT_docs#428](https://github.com/gmt-china/GMT_docs/issues/428)的原有内容。

Good~ 感觉你自己提交 PR，然后一点点改会更有效率。你那边网络在 GitHub 上提交 PR 是否有困难？或许有其他方面的考虑？

**Comment by liuzhumei** [comment]
> > 我参考了[gmt-china/GMT_docs#427](https://github.com/gmt-china/GMT_docs/pull/427) 的格式修改了中国断层数据集的描述、使用方法和构建流程，包含了 [gmt-china/GMT_docs#428](https://github.com/gmt-china/GMT_docs/issues/428)的原有内容。
> 
> Good~ 感觉你自己提交 PR，然后我们一点点在线审稿和修改会更有效率。你那边网络在 GitHub 上提交 PR 是否有困难？
> 或者有其他方面的考虑吗？例如 PR 提交流程不熟练，如果是这样，我可以提供一定帮助。

我唯一的困难是对文档的格式搞不清楚，我在本地预览md文件格式是好的，但似乎与网页上用的rst又不一样。 @seisman 给我一个在线转换文档格式的地址，但是天哪，怎么会有这么多名字相似的格式，我该用哪一个？之前他们也教过我在本地编译预览网页效果，但已经是几年前了，不知道还能不能成功。

**Comment by core-man** [comment]
> 我唯一的困难是对文档的格式搞不清楚，我在本地预览md文件格式是好的，但似乎与网页上用的rst又不一样。 @seisman 给我一个在线转换文档格式的地址，但是天哪，怎么会有这么多名字相似的格式，我该用哪一个？之前他们也教过我在本地编译预览网页效果，但已经是几年前了，不知道还能不能成功。

其实 rst 格式很容易学，可以参考 https://seismo-learn.org/contributing/restructuredtext/ ，基本 5 分钟速成了。而且你在 PR 提交后，我们可以帮你修改，经过一轮 PR，你肯定就全会了。

**Comment by seisman** [comment]
@liuzhumei 你打算自己改不？

**Comment by liuzhumei** [comment]
留给我改。我大概26号可以动笔。

Dongdong Tian ***@***.***>于2021年6月23日 周三22:32写道：
