### ISSUE TITLE
迁移社区网站的地学数据

### ISSUE THREAD

**Issue by core-man** [gmt-china/china-geospatial-data#5]
@CovMat 在 #4 一次性迁移了社区网站的[中国地学数据](https://gmt-china.org/data/)。我觉得我们可以更平缓地迁移数据，最好是每个数据用一个或多个PR迁移，请看以下初步想法：

## 数据集目录

当前目录设置：
- `figures`: 图片和脚本
- 数据文件：如 `CN_faults.gmt`

我认为应该每一类数据放置在一个目录下，以下是初步目录设置想法：

中国行政区：
- 中国国界、省界、十段线以及南海诸岛
- 国界、十段线以及南海诸岛数据（不含省界数据）
- 仅包含十段线数据
- 中国省会城市坐标

中国地震区域：
- 中国地震区域划分边界数据
- 中国地震区域划分名称数据
- 中国地震区域划分亚区边界数据
- 中国地震区域划分亚区边界数据

中国断层：
- 中国断层数据

中国铁路：
- 中国铁路线

中国河流：
- 中国一级河流数据

中国板块：
- 中国大陆一级地块边界数据
- 中国大陆一级地块推断边界数据
- 中国大陆二级地块边界数据

此外，脚本和图片不建议放在本数据仓库中，建议放在中文手册中，图片由ci自动生成在手册中。本仓库只用于存放数据文件、构建流程等。

## 迁移过程

迁移以上每一个数据的时候，我们大约需要三步(参考 https://github.com/gmt-china/GMT_docs/issues/301):

- china-geospatial-data 仓库：新建该数据集（参考下一节**新建数据集注意事项**）
- 中文手册：添加数据集的说明、绘图脚本、图片（自动生成）等 (https://github.com/gmt-china/GMT_docs/issues/302)
- 社区网站：
  - 设置中文社区网站对应的图库/博客自动跳转至新链接
  - [地学数据](https://gmt-china.org/data/)中给出数据集的新链接
  - [gmt-china.org/content/data](https://github.com/gmt-china/gmt-china.org/tree/master/content/data)中数据是否需要保留或者保留一段时间？

## china-geospatial-data 仓库新建数据集注意事项

- 构建流程
- 文件格式：`.gmt`
- 文件来源、引用

**Comment by seisman** [comment]
> 我觉得我们可以更平缓地迁移数据，最好是每个数据用一个或多个PR迁移

Yes.

> 我认为应该每一类数据放置在一个目录下

我个人比较倾向于将所有数据放在单个目录下，这样做的好处下载之后直接设置 GMT_DATADIR (https://docs.gmt-china.org/latest/dataset/overview/#setup-database) 即可使用。而如果是多目录就会麻烦很多。

> 此外，脚本和图片不建议放在本数据仓库中，建议放在中文手册中，图片由ci自动生成在手册中。本仓库只用于存放数据文件、构建流程等。

OK.

**Comment by core-man** [comment]
> > 我认为应该每一类数据放置在一个目录下
> 
> 我个人比较倾向于将所有数据放在单个目录下，这样做的好处下载之后直接设置 GMT_DATADIR (https://docs.gmt-china.org/latest/dataset/overview/#setup-database) 即可使用。而如果是多目录就会麻烦很多。

okay. 那我们就把所有数据直接放在仓库主目录下，还是新建一个目录放置所有数据。我倾向于新建一个目录，这样仓库主目录比较干净。

**Comment by seisman** [comment]
> okay. 那我们就把所有数据直接放在仓库主目录下，还是新建一个目录放置所有数据。我倾向于新建一个目录，这样仓库主目录比较干净。

直接放在根目录下的好处在于 git clone 后直接 export GMT_DATADIR="/path/to/repo" 即可使用，否则就得
export GMT_DATADIR="/path/to/repo/subdir".

**Comment by core-man** [comment]
> > okay. 那我们就把所有数据直接放在仓库主目录下，还是新建一个目录放置所有数据。我倾向于新建一个目录，这样仓库主目录比较干净。
> 
> 直接放在根目录下的好处在于 git clone 后直接 export GMT_DATADIR="/path/to/repo" 即可使用，否则就得
> export GMT_DATADIR="/path/to/repo/subdir".

我们可以先放在根目录，等以后数据很多的时候再考虑是否合适。

**Comment by core-man** [comment]
让我们先移动一个数据，才移动的过程中总结经验。我将在这个对话框中，**持续更新**数据库移动进展和列表：

## 中国国界

- 博客：[GMT自带中国国界问题](https://gmt-china.org/blog/china-border-issues/)
- 图库：[中国国界、省界及十段线](https://gmt-china.org/example/ex003/)
- 数据集：https://gmt-china.org/data/

**Comment by seisman** [comment]
OK.

**Comment by CovMat** [comment]
https://github.com/gmt-china/china-geospatial-data/pull/10

@core-man @seisman 先试一下移动一个

**Comment by core-man** [comment]
> @core-man @seisman 先试一下移动一个

接下来可以把国家的博客或者图库移动到中文手册中吗？我们一个一个数据搞定他们吧。

**Comment by core-man** [comment]
> 设置中文社区网站对应的图库/博客自动跳转至新链接
> 地学数据中给出数据集的新链接

@CovMat 在 #10  和 https://github.com/gmt-china/GMT_docs/pull/343# 迁移了国界数据。我们需要处理社区网站原始链接了，Ping @seisman @CovMat for comments.

**Comment by CovMat** [comment]
> > @core-man @seisman 先试一下移动一个
> 
> 接下来可以把上面两个国界相关的博客或者图库移动到中文手册中吗？我们一个一个数据搞定他们吧。

https://gmt-china.org/example/ex003/
https://gmt-china.org/blog/china-border-issues/

重定向上面两个链接？
@core-man

**Comment by core-man** [comment]
>> https://gmt-china.org/example/ex003/
> https://gmt-china.org/blog/china-border-issues/
> 
> 重定向上面两个链接？
> @core-man

yes to me.

----

另外，是否可以在 https://gmt-china.org/data/加上一个说明，列出数据库仓库以及手册的新链接

**Comment by CovMat** [comment]
我觉得
- 中国铁路线
- 中国一级河流数据
这两个数据没有实用价值，不用收入了

**Comment by core-man** [comment]
See https://github.com/gmt-china/gmt-china.org/pull/182#issuecomment-854370283:

> Do we want to keep the blog? https://gmt-china.org/blog/china-border-issues/

《GMT自带中国国界问题》中除了绘图脚本外，大部分文字迁移到 https://docs.gmt-china.org/latest/dataset-CN/CN-border/ 中了，是否也从定向？

---

> 中国铁路线

这个可能还有价值，目前高铁地震学比较火热。

> 中国一级河流数据

GMT 中有河流，不收录可以

**Comment by CovMat** [comment]
> See [gmt-china/gmt-china.org#182 (comment)](https://github.com/gmt-china/gmt-china.org/pull/182#issuecomment-854370283):
> 
> > Do we want to keep the blog? https://gmt-china.org/blog/china-border-issues/
> 
> 《GMT自带中国国界问题》中除了绘图脚本外，大部分文字迁移到 https://docs.gmt-china.org/latest/dataset-CN/CN-border/ 中了，是否也从定向？
> 
> > 中国铁路线
> 
> 这个可能还有价值，目前高铁地震学比较火热。
> 
> > 中国一级河流数据
> 
> GMT 中有河流，不收录可以

博客也重定向吧

铁路那个数据太老了，我一眼看过去，福建段就有很多条线路没有（八纵八横路线）。这么老的数据没必要吧

**Comment by core-man** [comment]
> 铁路那个数据太老了，我一眼看过去，福建段就有很多条线路没有（八纵八横路线）。这么老的数据没必要吧

如果数据本身太老，那就先不迁移。后面我们可以直接构建最新的铁路数据库。

**Comment by CovMat** [comment]
> See [gmt-china/gmt-china.org#182 (comment)](https://github.com/gmt-china/gmt-china.org/pull/182#issuecomment-854370283):
> 
> > Do we want to keep the blog? https://gmt-china.org/blog/china-border-issues/
> 
> 《GMT自带中国国界问题》中除了绘图脚本外，大部分文字迁移到 https://docs.gmt-china.org/latest/dataset-CN/CN-border/ 中了，是否也从定向？
> 
> > 中国铁路线
> 
> 这个可能还有价值，目前高铁地震学比较火热。
> 
> > 中国一级河流数据
> 
> GMT 中有河流，不收录可以
> 
> 下一个数据集，中国板块？请看上面更新的列表？

这个数据里有中文
中文会乱码，这样在手册里会非常难看。我想是不是可以不要中文，把里面的名词全用英文

**Comment by core-man** [comment]
我们投个票吧，哪些值得或者必要维护和迁移的？直接在后面签名表示同意迁移

## Done

- CN-border-La.dat: 中国国界、省界、十段线以及南海诸岛 
- CN-border-L1.dat: 国界、十段线以及南海诸岛数据（不含省界数据）
- ten-dash-line.dat: 仅包含十段线数据
- CN-faults.dat: 中国断层数据
 
## TODO

- CN-capitals.dat: 中国省会城市坐标
- CN-EQRegion.dat: 中国地震区域划分边界数据
- CN-EQRegion-name.dat: 中国地震区域划分名称数据
- CN-EQSubRegion.dat: 中国地震区域划分亚区边界数据
- CN-EQSubRegion-name.dat: 中国地震区域划分亚区边界数据
- CN-Railways.dat: 中国铁路线 （数据太老，建议重新构建最新版本）
- CN-Rivers.dat: 中国一级河流数据
- CN-block-L1.dat: 中国大陆一级地块边界数据 @core-man 
- CN-block-L1-deduced.dat: 中国大陆一级地块推断边界数据 @core-man 
- CN-block-L2.dat: 中国大陆二级地块边界数据 @core-man

**Comment by wangliang1989** [comment]
肯定是应该所有数据都尽量保留，命名要仔细考虑，我认为成都理工大学-地球物理学院-王亮这种形式比较好

**Comment by CovMat** [comment]
https://gmt-china.org/example/ex003/ 应该迁移到 https://docs.gmt-china.org/latest/dataset-CN/CN-border/

https://gmt-china.org/example/ex007/ 应该迁移到 https://docs.gmt-china.org/latest/dataset-CN/CN-faults/

@core-man

**Comment by core-man** [comment]
Hide comment 的好处是使对话框简洁，但是这样很多对话就看不到了。而且每个维护者对哪些对话框需要隐藏的理解也不同。因此，我把 hided 的comment取消隐藏了。此外，为了使对话框简洁明了，维护者们留言和评论时候也就要多思考一下，避免不必要的评论。

**Comment by core-man** [comment]
目前 TODO 里的数据库，我个人觉得都不需要迁移和维护了。因为我觉得维护的数据集需要有以下基本特征：
- 专业和科学，最好有官方或者论文支持
- 有效性，不能太陈旧
- 用户多，而不是小众数据集

如 **地震区域划分数据**并没有官方来源，而且我看 https://gmt-china.org/example/ex005/ 里分也很粗糙。

对于不符合数据集条件的，我们可以通过手册图库的实例来绘制其中一些有意思的数据集，比如中国省会城市。

**Comment by seisman** [comment]
Close?

**Comment by core-man** [comment]
I am okay to close it.
