### ISSUE TITLE
是否有更详细的CRS信息？

### ISSUE THREAD

**Issue by PlanetesDDH** [gmt-china/china-geospatial-data#58]
老师您好：
我在文章【屈春燕. 2008. 《最新1/400万中国活动构造空间数据库的建立》. 地震地质, 期 1: 298–304. 】了解到活动断层数据的相关信息：“在本数据库的建立过程中，我们使用了等面积圆锥投影，投影参数是：2条标准纬线分别为25°和47°，中央经线110°，原点纬线30°”。
为了更准确的使用该数据集，想问下是否有更详细的可用于定义CRS的信息，如WKT格式或者对应EPSG编号等。

我根据上述文章中的描述构造了一个，但是信息应该是不够全："+proj=aea +lat_1=25 +lat_2=47 +lat_0=30 +lon_0=110 +x_0=0 +y_0=0 +ellps=WGS84 +units=m"。

还请您多指教！

**Comment by ZMAlt** [comment]
CRS 是什么意思？

这个 repo 提供的数据应该都是 WGS-84 下的地理坐标，和投影没什么关系。您可以使用任意投影，包括上面描述的投影。

至于格式，我想应该不会另外提供其他格式的，目前已经足够使用。GMT 可以读取大多数矢量数据格式。如果不是在 GMT 用，也可以用 gmtconvert 或者 GDAL 的 ogr2ogr 转换成您想要的格式。

**Comment by PlanetesDDH** [comment]
> 所谓的CRS官方是Coordinate Reference System的意思，应该就是您提到的WGS-84，只是我使用geopandas来读取的shp（zip）文件，调取gdf（GeoDataFrame，geopandas中的表类型）坐标系属性，gdf.crs时为空，也就是需要自己设置原始数据的坐标系统CRS，以便进行后续的坐标转换操作。WGS-84在CRS中的代号为EPSG: 4326。

**Comment by ZMAlt** [comment]
https://github.com/gmt-china/china-geospatial-data/blob/82e91c75268bd0c5c90ed3e82e41048387b24856/ten-dash-line.gmt#L3-L4

部分数据有，断层的数据没有。

可以关闭了？
