### ISSUE TITLE
删除 GB2312 编码的文件？

### ISSUE THREAD

**Issue by seisman** [gmt-china/china-geospatial-data#8]
为了使 GMT 能够显示中文，Linux 和 macOS 用户需要使用 UTF8 编码的中文数据文件，而 Windows + BAT 用户则需要使用 GB2312 编码的中文数据文件。

基于这个原因， @CovMat 添加了 `CN_faults_GB2312.gmt` 文件。考虑到这个数据库中大部分数据都包含中文，为每个数据都准备 UTF8 和 GB2312 编码的文件会产生如下问题：

1. 整个 repo 中文件数目加倍
2. 整个 repo 的大小加倍
3. 用户在阅读这个 repo 时会出现两个版本的数据不知道该如何选择的问题
4. 对于任一用户而言，如果使用 git clone 或者下载 master.zip 的方式，会得到冗余文件（例如，Linux用户不需要 GB2312 文件）

考虑到以上问题，我建议：

1. 删除 GB2312 编码的文件
2. repo 中所有文件均使用 UTF8 编码
3. 当新增数据后，发布一个 release，并在 release 页面添加 UTF8 和 GB2312 两个版本的附件，供用户选择使用
4. 在 README 中强调 repo 中所有文件都是 UTF8 编码，并给出 Windows 用户需要的额外操作

**Comment by core-man** [comment]
> 3. 当新增数据后，发布一个 release，并在 release 页面添加 UTF8 和 GB2312 两个版本的附件，供用户选择使用


这是否意味着我们某个人要在本地维护GB2312版本？

**Comment by seisman** [comment]
并不需要，可以弄一个 workflow 在发布 release 的时候自动将所有数据转换为 GB2312，然后上传作为 release 的 assets

**Comment by core-man** [comment]
> 并不需要，可以弄一个 workflow 在发布 release 的时候自动将所有数据转换为 GB2312，然后上传作为 release 的 assets

okay. 我没问题。

**Comment by seisman** [comment]
@CovMat for comments.
